[package]
name = "bbtk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = [
    "alloc",
    "derive",
    "rc",
    "serde_derive",
] }
thiserror = "2.0"

[features]
serde = []
